### ISSUE TITLE
Error - SRM_S02

### ISSUE THREAD

**Issue by em1le** [crs4/hl7apy#49]
Good afternoon HL7apy team,

Does HL7apy supports SRM/SRR messages from S02 to S11?

```bash
>>> Message("SRM_S02")
Traceback (most recent call last):
  File "/Users/e/.virtualenvs/soft/lib/python3.7/site-packages/hl7apy/v2_5/__init__.py", line 41, in get
    return ELEMENTS[element_type][name]
KeyError: 'SRM_S02'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/e/.virtualenvs/soft/lib/python3.7/site-packages/hl7apy/core.py", line 546, in get_structure
    reference = load_reference(element.name, element.classname, element.version)
  File "/Users/e/.virtualenvs/soft/lib/python3.7/site-packages/hl7apy/__init__.py", line 280, in load_reference
    ref = lib.get(name, element_type)
  File "/Users/e/.virtualenvs/soft/lib/python3.7/site-packages/hl7apy/v2_5/__init__.py", line 43, in get
    raise ChildNotFound(name)
hl7apy.exceptions.ChildNotFound: No child named SRM_S02

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/e/.virtualenvs/soft/lib/python3.7/site-packages/hl7apy/core.py", line 1914, in __init__
    validation_level)
  File "/Users/e/.virtualenvs/soft/lib/python3.7/site-packages/hl7apy/core.py", line 1784, in __init__
    super(Group, self).__init__(name, parent, reference, version, validation_level, traversal_parent)
  File "/Users/e/.virtualenvs/soft/lib/python3.7/site-packages/hl7apy/core.py", line 638, in __init__
    self._find_structure(reference)
  File "/Users/e/.virtualenvs/soft/lib/python3.7/site-packages/hl7apy/core.py", line 813, in _find_structure
    structure = ElementFinder.get_structure(self, reference)
  File "/Users/e/.virtualenvs/soft/lib/python3.7/site-packages/hl7apy/core.py", line 548, in get_structure
    raise InvalidName(element.classname, element.name)
hl7apy.exceptions.InvalidName: Invalid name for Message: SRM_S02
```

**Comment by svituz** [comment]
Hi @em1le,
I quickly read the specification (Chapter 10 of the 2.5 version) and it seems that all the SRM/SRR messages have the same message structure, SRM_S01, (i.e., the same msh.9.3) which is the one used by hl7apy when instantiating the message. The difference is the trigger event which can range from S01 to S11. 
In other words, if you want, for example, a message with the trigger event S07 you should write:
```python 
>>> m = Message('SRM_S01')
>>> m.msh.msh_9.msh_9_1.value = 'SRM'
>>> m.msh.msh_9.msh_9_2.value = 'S07'
>>> m.msh.msh_9.msh_9_2.value = 'SRM_S01'
>>> print(m.to_er7())
'MSH|^~\&|||||20190702164829||SRM^S07^SRM_S01|||2.5'
```
If you try to use SRM_S02 you get the error, which I think is correct.

Vittorio

**Comment by em1le** [comment]
Thanks a lot Vittorio.

I close the issue as it was actually a misunderstanding of mine.
