### ISSUE TITLE
AttributeError: module 'hl7apy.v2_5' has no attribute 'get'

### ISSUE THREAD

**Issue by davidadamojr** [crs4/hl7apy#61]
I am seeing the following error/stacktrace when using hl7apy in a REST API written in Python3.7, running on a Flask/Gunicorn web server with 2 worker processes and multiple threads per worker.

```
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/middleware.py", line 189, in wrapped_f
    return f(*args, **kwargs)
  File "upload_api.py", line 60, in receive_message
    parsed_message = parse(appt_msg_hl7)
  File "hl7/parser.py", line 50, in parse
    return parse_message(message.replace('\n', '\r'), find_groups=False)
  File "venv/lib/python3.7/site-packages/hl7apy/parser.py", line 82, in parse_message
    validation_level=validation_level, encoding_chars=encoding_chars)
  File "venv/lib/python3.7/site-packages/hl7apy/core.py", line 1914, in __init__
    validation_level)
  File "venv/lib/python3.7/site-packages/hl7apy/core.py", line 1784, in __init__
    super(Group, self).__init__(name, parent, reference, version, validation_level, traversal_parent)
  File "venv/lib/python3.7/site-packages/hl7apy/core.py", line 638, in __init__
    self._find_structure(reference)
  File "venv/lib/python3.7/site-packages/hl7apy/core.py", line 813, in _find_structure
    structure = ElementFinder.get_structure(self, reference)
  File "venv/lib/python3.7/site-packages/hl7apy/core.py", line 546, in get_structure
    reference = load_reference(element.name, element.classname, element.version)
  File "venv/lib/python3.7/site-packages/hl7apy/__init__.py", line 280, in load_reference
    ref = lib.get(name, element_type)
AttributeError: module 'hl7apy.v2_5' has no attribute 'get'
```
Some other useful information:
* I am able to successfully parse the offending messages on my local setup, so this only seems to happen in my multithreaded production environment. 
* This error also occurs with hl7apy.v2_4, so it is not peculiar to hl7apy.v2.5.
* This problem is intermittent i.e. messages are parsed successfully 90% of the time, but there are a few so-far-unpredictable instances where this error occurs at runtime.

Could it be that certain aspects of the hl7apy implementation are not thread-safe? Is hl7apy thread-safe? Or is this caused by something else entirely that I may be overlooking? Please help!

**Comment by svituz** [comment]
Hi @davidadamojr,
it seems you're right, something bad happens when running hl7apy in a multithreaded environment. I'll have to figure out the problem.

**Comment by davidadamojr** [comment]
Thanks for taking a look. Please let me know if you need any more information, or if there is some other way I can help.

**Comment by jcbeaury** [comment]
Blast from the past - @svituz can you release this please?

**Comment by svituz** [comment]
@jcbeaury released yesterday
